name: Build and Deployment
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      inputTag:
        description: "Optional: Docker tag to deploy (leave empty to use artifact)"
        required: false
        default: ""

jobs:
  build:    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout      
        if: ${{ github.event.inputs.inputTag == '' }}
        uses: actions/checkout@v4      

      - name: Set up .NET Core
        if: ${{ github.event.inputs.inputTag == '' }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
         
      - name: Build with dotnet
        if: ${{ github.event.inputs.inputTag == '' }}
        run: dotnet build --configuration Release  

      - name: Setup Docker Buildx
        if: ${{ github.event.inputs.inputTag == '' }}
        uses: docker/setup-buildx-action@v3 

      - name: Login to ACR
        if: ${{ github.event.inputs.inputTag == '' }}
        uses: docker/login-action@v3
        with:
          registry: twdotnetregistry.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Generate Docker Tag
        id: tag        
        if: ${{ github.event.inputs.inputTag == '' }}
        run: |
          # Example: Using commit SHA as tag
          DOCKER_TAG=${{ github.sha }}
          echo "DOCKER_TAG=$DOCKER_TAG" >> $GITHUB_OUTPUT
          echo "$DOCKER_TAG" > docker_tag.txt     

      - name: Build and push container image to ACR
        if: ${{ github.event.inputs.inputTag == '' }}
        uses: docker/build-push-action@v6
        with:          
          push: true
          tags: twdotnetregistry.azurecr.io/webapplication1:${{ steps.tag.outputs.DOCKER_TAG }}
          file: WebApplication1/Dockerfile
         
      - name: Upload Docker Tag Artifact
        if: ${{ github.event.inputs.inputTag == '' }}
        uses: actions/upload-artifact@v4
        with:
          name: docker-tag-artifact
          path: docker_tag.txt      

  get-tag:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      docker_tag: ${{ steps.set_tag.outputs.docker_tag }}

    steps:
      - name: Show input
        run: echo "Input Tag = '${{ github.event.inputs.inputTag }}'"

      # If no inputTag → download artifact
      - name: Download docker tag artifact
        if: ${{ github.event.inputs.inputTag == '' }}
        uses: actions/download-artifact@v4            
        with:
          name: docker-tag-artifact          
          path: ./artifact     

      - name: Read artifact tag
        if: ${{ github.event.inputs.inputTag == '' }}
        id: artifact_tag
        run: |
              TAG=$(cat artifact/docker_tag.txt)
              echo "tag=$TAG" >> $GITHUB_OUTPUT

      # Choose final tag
      - name: Set final docker tag
        id: set_tag
        run: |
              if [ -z "${{ github.event.inputs.inputTag }}" ]; then
                FINAL="${{ steps.artifact_tag.outputs.tag }}"
              else
                FINAL="${{ github.event.inputs.inputTag }}"
              fi
              echo "docker_tag=$FINAL" >> $GITHUB_OUTPUT

      - name: Show final tag
        run: echo "Final Docker Tag = ${{ steps.set_tag.outputs.docker_tag }}"

  deploy-staging:
    needs: get-tag
    runs-on: ubuntu-latest
    environment: staging # Use selected environment or default
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

        #- name: Pull Docker image
        #  run: docker pull your-docker-username/your-image-name:latest

      - name: Deploy to staging
          # Replace with your specific deployment commands for each environment
          # This could involve SSHing to a server, updating a Kubernetes deployment, etc.
        run: echo "Deploying to staging...${{ needs.get-tag.outputs.docker_tag }}"
 
  deploy-uat:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment: uat # Use selected environment or default
    permissions:      # ⬅️ REQUIRED HERE
      id-token: write
      contents: read
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to uat
        uses: azure/container-apps-deploy-action@v1
        with:
          resourceGroup: rg-ca
          containerAppName: twapi-stg
          imageToDeploy: twdotnetregistry.azurecr.io/webapplication1:${{ needs.get-tag.outputs.docker_tag }}

      #- name: Deploy to uat
          # Replace with your specific deployment commands for each environment
          # This could involve SSHing to a server, updating a Kubernetes deployment, etc.
       # run: | 
       #       echo "Deploying to uat...${{ needs.get-tag.outputs.docker_tag }}"

  deploy-production:
    needs: deploy-uat
    runs-on: ubuntu-latest
    environment: production # Use selected environment or default
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

        #- name: Pull Docker image
        #  run: docker pull your-docker-username/your-image-name:latest

      - name: Deploy to production
          # Replace with your specific deployment commands for each environment
          # This could involve SSHing to a server, updating a Kubernetes deployment, etc.
        run: echo "Deploying to production...${{ needs.get-tag.outputs.docker_tag }}"

