name: Workflow A

on:
  push:
    branches: [main]

jobs:
  producer:
    runs-on: ubuntu-latest

    steps:
      - name: Create value file
        run: echo "myvalue=12345" > value.txt

      - name: Upload value
        uses: actions/upload-artifact@v4
        with:
          name: shared-value
          path: value.txt